In [1]:
##1.




def safe_divide(a, b):
    try:
        print("Result:", a / b)
    except ZeroDivisionError:
        print("Cannot divide by zero.")
    except TypeError:
        print("Inputs must be numbers.")
    finally:
        print("Operation attempted.")

# Test Cases
safe_divide(10, 2)
safe_divide(10, 0)
safe_divide(10, "2")


Result: 5.0
Operation attempted.
Cannot divide by zero.
Operation attempted.
Inputs must be numbers.
Operation attempted.


In [2]:
## 2
# Custom Exception Class
class InvalidAgeError(Exception):
    pass

# Function to validate age
def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Invalid Age!")
    else:
        print("Valid Age:", age)

# Test with 3 different values
ages = [25, -5, 150]

for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print("Error:", e)

Valid Age: 25
Error: Invalid Age!
Error: Invalid Age!


In [3]:
#3..
user_inputs = ['10', 'abc', '0', '5']
for value in user_inputs:
    try:
        number = int(value)      
        result = 100 / number    
        print("Result:", result)
    except ValueError:
        print("Error: Input is not a valid number.")
    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")
    except Exception as e:
        print("Error:", e)

Result: 10.0
Error: Input is not a valid number.
Error: Cannot divide by zero.
Result: 20.0


In [4]:
##4...



import numpy as np
arr = np.arange(1, 21)
print("Original 1D Array:")
print(arr)
arr = arr.reshape(4, 5)
print("\n4x5 Array:")
print(arr)
# (b) Print the sum of each row and each column
print("\nSum of Each Row:")
print(np.sum(arr, axis=1))

print("\nSum of Each Column:")
print(np.sum(arr, axis=0))

# (c) Extract elements greater than 10
print("\nElements Greater Than 10:")
print(arr[arr > 10])

# (d) Replace all even numbers with -1
arr[arr % 2 == 0] = -1

print("\nArray After Replacing Even Numbers with -1:")
print(arr)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

4x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sum of Each Row:
[15 40 65 90]

Sum of Each Column:
[34 38 42 46 50]

Elements Greater Than 10:
[11 12 13 14 15 16 17 18 19 20]

Array After Replacing Even Numbers with -1:
[[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]]


In [5]:
###5..

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# (a) Element-wise operations
print("Addition:")
print(np.add(A, B))

print("\nSubtraction:")
print(np.subtract(A, B))

print("\nMultiplication:")
print(np.multiply(A, B))

# (b) Matrix Multiplication
print("\nMatrix Multiplication:")
print(np.dot(A, B))

# (c) Transpose of A
print("\nTranspose of A:")
print(np.transpose(A))

# (d) Determinant of A
print("\nDeterminant of A:")
print(np.linalg.det(A))

# Inverse of A
print("\nInverse of A:")
print(np.linalg.inv(A))

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
##6..

import numpy as np
np.random.seed(42)
arr = np.random.randint(1, 101, 15)

print("Original Array:")
print(arr)

# (a) Mean, Median, Standard Deviation, Minimum, Maximum
print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

# (b) Sort the array in descending order
print("\nArray in Descending Order:")
print(np.sort(arr)[::-1])

# (c) Indices of the 3 largest values
print("\nIndices of 3 Largest Values:")
print(np.argsort(arr)[-3:])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print("\nNormalized Array:")
print(normalized)

Original Array:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

Mean: 58.06666666666667
Median: 72.0
Standard Deviation: 31.4843170836247
Minimum: 3
Maximum: 100

Array in Descending Order:
[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

Indices of 3 Largest Values:
[10  1 11]

Normalized Array:
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


In [8]:
###7


import pandas as pd

# Create DataFrame
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)
# (a) Display first 3 rows
print("First 3 Rows:")
print(df.head(3))
# Display data types
print("\nData Types:")
print(df.dtypes)
# (b) Add Grade column
grade = []
for score in df["Score"]:
    if score >= 90:
        grade.append("A")
    elif score >= 75:
        grade.append("B")
    else:
        grade.append("C")
df["Grade"] = grade
print("\nDataFrame with Grade:")
print(df)
# (c) Sort by Score in descending order
print("\nSorted by Score:")
print(df.sort_values(by="Score", ascending=False))

# (d) Filter rows where Department is AI
print("\nDepartment = AI:")
print(df[df["Department"] == "AI"])

First 3 Rows:
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data Types:
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade:
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by Score:
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

Department = AI:
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [9]:
##8


import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# (a) Average score of each department
print(df.groupby("Department")["Score"].mean())

# (b) Row with highest score
print(df.loc[df["Score"].idxmax()])
# (c) Rename Score to Marks
df = df.rename(columns={"Score": "Marks"})
print(df)
# (d) Drop Age column
df = df.drop("Age", axis=1)
print(df)






Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64
Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object
    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67
    Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [10]:
###9..

import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# (a) Check missing values
print(df.isnull().sum())
# (b) Fill missing Price with mean
df["Price"] = df["Price"].fillna(df["Price"].mean())
# (c) Drop rows where Stock is missing
df = df.dropna(subset=["Stock"])
# (d) Save to CSV
df.to_csv("cleaned_products.csv", index=False)

print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


In [11]:
###10..


import pandas as pd
try:
    df = pd.read_csv("cleaned_products.csv")
    print("Shape:", df.shape)
    print("Columns:", df.columns)
    df["Total_Value"] = df["Price"] * df["Stock"]
    print(df)
    print(df.describe())

except FileNotFoundError:
    print("Error: cleaned_products.csv file not found.")

Shape: (4, 3)
Columns: Index(['Product', 'Price', 'Stock'], dtype='object')
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
