In [1]:
#Num Py

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
# creating Arrays 

In [6]:
sample_array = np.array([1,2,3,4])

In [7]:
sample_array

array([1, 2, 3, 4])

In [8]:
sample_array2 = np.array([2,3,4,5,6])

In [9]:
sample_array2

array([2, 3, 4, 5, 6])

In [10]:
# 2D Array(a Matrix) with two rows and two columns

In [12]:
sample_array_3 = np.array([[1,2],[3,4]])

In [13]:
sample_array_3

array([[1, 2],
       [3, 4]])

In [14]:
sample_array_4 = np.array([[3,4],[5,6]])

In [15]:
sample_array_4

array([[3, 4],
       [5, 6]])

In [16]:
# 3D tensor  (2 matrices, each with 2 rows and 2 columns)

In [17]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [18]:
sample_tensor_3 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
# Dimension

In [21]:
# 0 - D array(scalar) {5} only one elements are presents 
# 1 - D array(vector) [1,2,3,4] 
# 2 - D array(Matrix) (rows, columns)
# 3 - D array(tensor) (row,column, like a page )

In [22]:
# array properties

In [23]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [24]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# shape

In [26]:
sample_array.shape

(2, 3)

In [27]:
# dimensions 

In [29]:
sample_array.ndim # show the dimensions


2

In [30]:
# total elements 

In [32]:
sample_array.size

6

In [33]:
# data type 


In [36]:
sample_array.dtype

dtype('int64')

In [ ]:
# 3d

In [35]:
sample_tensor_3 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
# special arrays

In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [46]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [47]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [48]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [51]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [52]:
# indexing and slicing 

In [53]:
sample_array = np.array([10,20,30,40])

In [54]:
sample_array

array([10, 20, 30, 40])

In [55]:
sample_array[0]

np.int64(10)

In [56]:
sample_array[2]

np.int64(30)

In [58]:
sample_array[-1]

np.int64(40)

In [59]:
# slicing 


In [60]:
sample_array[1:3]

array([20, 30])

In [61]:
sample_array[0:-1]

array([10, 20, 30])

In [62]:
# array operations

In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [64]:
a

array([1, 2, 3])

In [65]:
b

array([4, 5, 6])

In [67]:
a + b

array([5, 7, 9])

In [68]:
a - b

array([-3, -3, -3])

In [69]:
a * b

array([ 4, 10, 18])

In [71]:
a / b

array([0.25, 0.4 , 0.5 ])

In [73]:
a = np.array([5,6,7])
b = np.array([8,9,10])

In [74]:
a


array([5, 6, 7])

In [75]:
b

array([ 8,  9, 10])

In [76]:
a + b

array([13, 15, 17])

In [77]:
a - b

array([-3, -3, -3])

In [78]:
a * b

array([40, 54, 70])

In [79]:
a / b

array([0.625     , 0.66666667, 0.7       ])

In [80]:
# Mathematical functions

In [81]:
sample_array = np.array([1,4,9])

In [82]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [85]:
sample_array = np.array([16,25,64])

In [86]:
np.sqrt(sample_array)

array([4., 5., 8.])

In [87]:
np.exp(sample_array)

array([8.88611052e+06, 7.20048993e+10, 6.23514908e+27])

In [88]:
np.log(sample_array)

array([2.77258872, 3.21887582, 4.15888308])

In [89]:
# statistical functions 

In [90]:
sample_array = np.array([1,2,3,4,5])

In [91]:
sample_array

array([1, 2, 3, 4, 5])

In [92]:
np.mean(sample_array)

np.float64(3.0)

In [93]:
np.median(sample_array)


np.float64(3.0)

In [95]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [96]:
np.min(sample_array)

np.int64(1)

In [97]:
np.max(sample_array)

np.int64(5)

In [98]:
# reshaping arrays 

In [100]:
sample_array = np.arange(6)

In [101]:
sample_array


array([0, 1, 2, 3, 4, 5])

In [103]:
reshaped = sample_array.reshape(2,3)

In [104]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [105]:
# flattening

In [106]:
sample_array = np.array([[1,2],[3,4]])

In [107]:
sample_array

array([[1, 2],
       [3, 4]])

In [108]:
sample_array.flatten()

array([1, 2, 3, 4])

In [109]:
sample_array = np.array([[4,5],[6,7]])

In [110]:
sample_array

array([[4, 5],
       [6, 7]])

In [111]:
sample_array.flatten()

array([4, 5, 6, 7])

In [112]:
sample_array = np.array([[[1,2],[3,4],[5,6]]])

In [113]:
sample_array

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [114]:
sample_array.flatten()

array([1, 2, 3, 4, 5, 6])

In [115]:
# joining arrays

In [116]:
a = np.array([1,2])
b = np.array([3,4])

In [117]:
a


array([1, 2])

In [118]:
b

array([3, 4])

In [119]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [120]:
# spliting arrays                           

In [121]:
sample_array = np.array([1,2,3,4])

In [122]:
sample_array

array([1, 2, 3, 4])

In [124]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [125]:
#  random module

In [126]:
np.random.rand(3)

array([0.59750676, 0.94273761, 0.39069346])

In [127]:
np.random.randint(1,10,5)


array([4, 3, 7, 4, 5], dtype=int32)

In [128]:
# axis concept

In [129]:
sample_array = np.array([[1,2],[3,4]])

In [130]:
sample_array

array([[1, 2],
       [3, 4]])

In [131]:
np.sum(sample_array, axis = 0)

array([4, 6])

In [133]:
np.sum(sample_array,axis = 1)

array([3, 7])

In [134]:
# NaN & Missing values 

In [135]:
sample_array = np.array([1,np.nan,3])

In [136]:
sample_array

array([ 1., nan,  3.])

In [137]:
np.isnan(sample_array)

array([False,  True, False])

In [139]:
a = np.array([1,2,3])
b = np.array([3,4,5])

In [140]:
a + b

array([4, 6, 8])

In [141]:
a - b

array([-2, -2, -2])

In [142]:
a * b

array([ 3,  8, 15])

In [7]:
import numpy as np

In [8]:
  a = np.arange (1000000)
  l = list(a)

In [9]:
import time
time.time()

1781588589.6018426

In [16]:
# time taken by list


start_time = time.time()
newl  = [i*2 for i in l]
time_taken_l =  time.time() - start_time

print (f" time taken by list is {time_taken_l}")

 time taken by list is 0.07286763191223145


In [17]:
# time taken by array

start_time = time.time()
newa = a*2
time_taken_a =  time.time() - start_time

print (f" time taken by an array is {time_taken_a}")

 time taken by an array is 0.0029189586639404297


In [18]:
# how much faster

In [19]:
time_taken_l / time_taken_a

24.963571020174793